### ISSUE TITLE
Colorscheme

### ISSUE THREAD

**Issue by Nekketsu** [jonboh/nvim-dap-rr#1]
Sorry for opening an issue for this, but, what colorscheme are you using in the screenshot?

**Comment by jonboh** [comment]
No problem, I use [folke's tokionight](https://github.com/folke/tokyonight.nvim) with the Night style and a sligth modification for the line numbers, check the [color config](https://github.com/jonboh/dotfiles/blob/6fe8c06072e80ca8ebb163ebefcbf1c113d42fc2/.config/nvim/after/plugin/color.lua) of my nvim if you want to copy it :)

**Comment by Nekketsu** [comment]
Thank you very much! It looks really cool!
