### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Lubsch** [jonboh/nvim-dap-rr#2]
I would really appreciate if you could add a license please, so this could be packaged.
Thank you

**Comment by jonboh** [comment]
Sure, MIT should be alright :), are you packaging for Nix?

**Comment by Lubsch** [comment]
Thanks :) yes I'm using NixOS and you can see what I'm using now in [my Config](https://github.com/Lubsch/nixos-config/blob/main/pkgs/nvim-dap-rr.nix). I have generated that file using [Nix-Init](https://github.com/nix-community/nix-init) btw. I've actually never contributed to nixpkgs, but maybe I will add this package if I find the time :)
