### ISSUE TITLE
request for better documentation for "alternative program picker"

### ISSUE THREAD

**Issue by dlyongemallo** [jonboh/nvim-dap-rr#5]
Currently, the documentation simply says one can skip telescope as a dependency if an alternative program is provided using the `program` field in the DAP configuration. However, it's not clear how to do this. Also, it seems `require("telescope.pickers")` is hardcoded into the plugin, so a module not found error is triggered even if `program` is set to something other than `find_program` (which is the only code using the pickers).

It would be nice to have a simple example of using something other than telescope in the README.md.

FYI: I use [FZF](https://github.com/junegunn/fzf) with [Fzf-Lua](https://github.com/ibhagwan/fzf-lua).

**Comment by jonboh** [comment]
I've pushed a new version that should not have telescope as a hard dependency 071e2ce.

The `program` option in nvim-dap expects to get the path of the executable. So you'll need to write a function that using fzf-lua returns the path to the executable. I haven't used fzf-lua but it probably has a picker that is able to do that.
As an alternative to the telescope picker I've added `vim.fn.input` that simply asks the user to write the path of the executable.
```lua
find_program = function()
  return vim.fn.input("Path to executable: ", vim.fn.getcwd() .. "/", "file")
end
-- afterwards `find_program` is passed to `program` in the dap configuration 
```

So you need to do something like this in your configuration (assuming the program picker is the only thing you want to change):
```lua
table.insert(dap.configurations.cpp, rr_dap.get_config(
    {
        program = function()
          -- call fzf-lua picker and return the selected path. 
          -- something similar to fzf-lua.files, but instead of opening the file in a buffer, simply return its path to the caller. 
          end,
    }
))
```

Let me know how it goes, I'll be happy to add the fzf lua function as an example in the readme for future reference

**Comment by dlyongemallo** [comment]
Oh, wait, I was misled by the description of the `program` field as a "program picker", but it's really just the `program` field of the DAP configuration, isn't it? In that case, I don't actually need FZF or any program picker at all.

Here's what I have already set `program` to in `dap.configurations.rust`:

```lua
local build_rust_program = function()
    local out = vim.fn.system({"cargo", "build"})
    if vim.v.shell_error ~= 0 then
        vim.notify("Build failed:\n" .. out, vim.log.levels.ERROR)
        return nil
    end
    return vim.fn.getcwd() .. "/target/debug/[executable_file_name]"
end
```

And here's what I have for `dap.configurations.cpp`:

```lua
local build_cpp_program = function()
    local out = vim.fn.system({"cmake", "--build", "."})
    if vim.v.shell_error ~= 0 then
        vim.notify("Build failed:\n" .. out, vim.log.levels.ERROR)
        return nil
    end
    return vim.fn.getcwd() .. "/bin/[executable_file_name]"
end
```

After updating to your new version, setting `program` to these works like a charm. 

I think the description in README.md should be made clear that all that's needed for `program` is a function that returns a path to the executable to be debugged. Based on the current description of it as a "picker", and on the `telescope.pickers` module not found error message, I had thought it was necessary to supply a UI file picker, which isn't actually needed.

Thanks for your help!

**Comment by jonboh** [comment]
I'll update the readme to clarify what `program` expects. 
Happy to help :)
